# Generated by Django 3.2.4 on 2021-06-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='expertai_sentiment',
        ),
        migrations.AddField(
            model_name='review',
            name='expertai_sentiment_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
